### ISSUE TITLE
address auto complete

### ISSUE THREAD

**Issue by VTskier** [LSVermont/docassemble-VTDivorce#152]
On the Suffolk server, the address auto complete works on a screen such as id: Gather users street or mailing address
(address autocomplete: True)

But on the vtcourtforms server, the auto complete doesn't work for that screen.
https://apps.vtcourtforms.org/run/VTDivorce/#/10

Any idea why?

**Comment by nonprofittechy** [comment]
We need to set you up with a Google API key

**Comment by nonprofittechy** [comment]
I configured you with an API key that I own for now, which should be fine (you need a lot of usage for this to be payable).
